server:
  port: 50003
spring:
  application:
    name: gateway-server
  profiles:
      active: publish

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    preferIpAddress: false
#    health-check-url-path: /actuator/health
#    home-page-url-path: /actuator
#    status-page-url-path: /actuator/info


#  sleuth:
#    sampler:                                    #日志记录
#      percentage: 1.0
#  zipkin:
#    base-url: http://localhost:9411
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
zuul:
  routes:
    order:
      path: /order/**
      serviceId: t-order     #订单服务
    shop:
      path: /order/**
      serviceId: t-shop      #商家服务
    coupon:
      path: /coupon/**
      serviceId: t-coupon    #折扣券服务
    items:
      path: /items/**
      serviceId: t-items     #商品服务
    user:
      path: /user/**
      serviceId: t-user
    auth:
      path: /auth/**
      serviceId: medusa-auth
  prefix: /api/ #为zuul设置一个公共的前缀
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000



