server:
  port: 8761
spring:
  profiles:
    active: daily
eureka:
  environment: daily
  server:
    enable-self-preservation: false           # 中小规模下，自我保护模式坑比好处多，所以关闭它
    eviction-interval-timer-in-ms: 5000       # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）从服务列表中剔除
    use-read-only-response-cache: false       # 禁用readOnlyCacheMap
  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 没有心跳的淘汰时间，10秒，即服务续约到期时间（缺省为90s）
    hostname: localhost
#    metadata-map:
#          user.name: admin
#          user.password: admin
#    health-check-url-path: /actuator/health
#    home-page-url-path: /actuator
#    status-page-url-path: /actuator/info
  client:
    registerWithEureka: false
    fetchRegistry: false
#    service-url:
#      defaultZone: ${defaultZone:http://peer2:8760/eureka/}